services:
  postgres:
    container_name: runner-db
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: runner

  redis:
    container_name: runner-redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always

  cpp:
    build:
      context: ./packages/runner/cpp
      dockerfile: Dockerfile

  rust:
    build:
      context: ./packages/runner/rust
      dockerfile: Dockerfile
