import type { Metadata } from "next";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { Footer } from "@/components/footer";
import { Toaster } from "@/components/ui/sonner";
import { UserDock } from "@/components/user-dock";
import { ThemeProvider } from "@/providers/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex flex-col min-h-screen justify-between scroll-smooth">
        <NextIntlClientProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
            {children}
            <Toaster />
            <UserDock />
            <Footer />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
